openapi: 3.0.0
info:
    version: 1.0.0
    title: Inventory Service
    description: Inventory Service API

servers:
    - url: http://localhost:3002/

paths:
    /inventory/{id}:
        get:
            summary: Get TF2 inventory of a user by steam ID
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: A list of items
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Item"
components:
    schemas:
        Item:
            type: object
            required:
                - name
                - image_url
                - level
                - quantity
            properties:
                name:
                    type: string
                custom_name:
                    type: string
                image_url:
                    type: string
                level:
                    type: integer
                quantity:
                    type: integer
