FROM golang:1.22.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /inventoryservice

FROM golang:1.22.3-alpine

COPY --from=builder /inventoryservice /inventoryservice
COPY --from=builder /app/.env .

EXPOSE 3003

CMD ["/inventoryservice"]