FROM node:18.19.0-slim

WORKDIR /app

COPY gateway/ gateway/

WORKDIR /app/gateway
RUN npm install

WORKDIR /app
COPY inventory.proto .

RUN --mount=type=secret,id=serviceAccountKey.json,dst=/etc/secrets/serviceAccountKey.json cat /etc/secrets/serviceAccountKey.json

EXPOSE 3002

WORKDIR /app/gateway
CMD ["npm", "start"]